image: openjdk:8-jdk

stages:
  - build
  - build_and_test

cache:
  paths:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

job_test:
  stage: build_and_test
  tags:
    - docker
  before_script:
    - java -version
  script:
    - ./gradlew clean test --fail-fast
