image: openjdk:8-jdk

stages:
  - build
  - build_and_test

variables:
  MAVEN_OPTS: "--batch-mode -Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

job_test:
  stage: build_and_test
  tags:
    - docker
  before_script:
    - java -version
  script:
    - ./mvnw $MAVEN_OPTS clean test
