image: openjdk:8-jdk

stages:
  - build
  - build_and_test

cache:
  paths:
    - .m2/repository/

services:
  - redis:alpine

job_test:
  stage: build_and_test
  tags:
    - docker
  before_script:
    - java -version
  script:
    - ./mvnw -B -Dmaven.repo.local=.m2/repository -DLOG_LEVEL=WARN -DREDIS_SINGLE_SERVER=redis:6379 clean test
